# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Phongphun Kijsanayothin
tagline:             ''
description:         ''
url:                 http://kphongph.github.io
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Phongphun Kijsanayothin
  url:               https://kphongph.github.io
  email:             

# Custom vars
version:             1.0.0
